version: '3.9'

services:
  app:
    container_name: app
    image: marcelofabianov/php8.3-fpm:latest
    build:
      context: ./_docker/local/php
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/var/www
      - ./.zshrc:/home/dev/.zshrc
      - ./.zsh_history:/home/dev/.zsh_history
    ports:
      - "8000:8000"
    networks:
      - app_network
    depends_on:
      - db

  db:
    container_name: db
    image: 'postgres:15-alpine'
    ports:
      - '5551:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE:-app_db}'
      POSTGRES_USER: '${DB_USERNAME:-user}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'app_db:/var/lib/postgresql/data'
    networks:
      - app_network

volumes:
  app_db:
    driver: local

networks:
  app_network:
    driver: bridge
